import type { Metadata } from "next";
import "./styles/globals.css";
import NextAuthSessionProvider from "./components/NextAuthProvider";

export const metadata: Metadata = {
  title: "Incog-Talk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='min-h-screen min-w-[380px]'>
        <NextAuthSessionProvider>
          {children}
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
